### ISSUE TITLE
'Like' is not translated

### ISSUE THREAD

**Issue by Abu-Abdullah** [boussaid/XF2_ARABIC#1]
السلام عليكم

هذي مفقودة وجدا مهمة
reaction_title.1

Like
أعجبني

**Comment by boussaid** [comment]
عليكم السلام
التفاعلات لا تعرب من ملف اللغة لأنها متغيرة
يتم تعديلها من المحتوى - التفاعلات
و هناك ضع ما تشاء .... مثل الإنذارات و سلم الالقاب .. الخ

**Comment by Abu-Abdullah** [comment]
شكرا أخي الكريم
لا أدري لكنها تظهر لي في العبارات الغير معدلة
كما أنه يمكنك مشاهدتها عند تصدير ملف اللغة

[language-Arabic.zip](https://github.com/boussaid/XF2_ARABIC/files/4802408/language-Arabic.zip)

**Comment by Abu-Abdullah** [comment]
أتكلم عن هذه
![Capture](https://user-images.githubusercontent.com/2059463/85096575-bcc79b00-b205-11ea-8698-7d5dd0b2bd8d.PNG)

وليس هذه
![Capture2](https://user-images.githubusercontent.com/2059463/85096580-c3561280-b205-11ea-8fcc-4563c6141e51.PNG)

**Comment by boussaid** [comment]
نعم أخي الكريم … 
هذه عبارات متغيرة  التفاعلات و الجوائز و الانذارات كلها عبارات متغيرة بحيث اذا تم تعريبها من ملف اللغة لن يستطيع المستخدم تخصيصها بما يناسبه.
ادخل كما قلت لك في اللوحة للمحتوى ثم اختر التفاعلات و عدل التفاعل Like و سمه أعجبني و قم بالحفظ، ثم عد للعبارة ستجد محتواها قد تغير تلقائياً، إذا عدلناها من ملف اللغة مباشرة لن تتغير العبارة مهما عدلت الخيار.

**Comment by Abu-Abdullah** [comment]
شكرا أخي الكريم
